name: Go

env:
  GOPRIVATE: "github.com/mlv9/protobuf"

on:
  push:
    branches: [ ISS-3 ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Configure git for private golang modules
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        USERNAME: ${{ github.repository_owner }}
      run: git config --global url."https://${USERNAME}:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push grpc-server
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./grpc-server
        file: ./grpc-server/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/grpc-server:latest
