name: Go

on:
  push:
    branches: [ ISS-1 ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout Protobuf
      uses: actions/checkout@v2
      with:
        repository: 'github.com/mlv9/protobuf'
        ref: 'master'
        ssh-key: ${{secrets.PROTOBUF_DEPLOY_KEY}}
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
